config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing'
  get 'pages/about_us'
  get 'pages/about_coffee'
  get 'pages/about_bcr'
  get 'pages/contact'
  post 'pages/contact', to: 'pages#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :first_name, :validate => true
  attribute :last_name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :message
  attribute :nickname, :captcha  => true

  def headers
    {
      :subject => "BCR.com",
      :to => "duvalwcash@gmail.com",
      :from => %("#{first_name + " " + last_name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  end

  def about_us
  end

  def about_coffee
  end

  def about_bcr
  end

  def contact
    @contact = ContactForm.new(params[:contact_form])
  end

  def create
    @contact = ContactForm.new(params[:contact_form])
    @contact.request = request

    respond_to do |format|
      if @contact.deliver
        format.html { redirect_to :root, notice: "Thank you for your message, we shall get back to shortly!" }
      else
        format.html { render 'contact', alert: "Message did not send, please try again." }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
    when "notice" then "is-notice"
    when "success" then "is-success"
    when "error" then "is-error"
    when "alert" then "is-error"
    end
  end

  def copyright_helper
    "\u00A9 Copyright Bahamas Coffee Roasters " + Time.now.year.to_s + ". All rights reserved."
  end

  def active? path
    "is-active" if current_page? path
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div id="notification" class="container">
    <div class="notification <%= flash_class(key) %>">
      <button class="delete"></button>
      <%= value %>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="hero-foot">
  <nav class="tabs is-boxed is-fullwidth">
    <div class="container">
      <ul>
        <li><%= link_to "#{copyright_helper}", "https://github.com/bvdmind/bahamas-coffee-roasters", :target => "_blank" %></li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navbar.html.erb
<div class="hero-head">
  <header class="navbar">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item">
          <%= link_to "< BCR >", root_path, class: "navbar-item" %>
        </a>
        <span class="navbar-burger burger" data-target="main-nav">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </div>
      <div id="main-nav" class="navbar-menu">
        <div class="navbar-end">
          <%= link_to "Home", root_path, class: "navbar-item #{active? root_path}" %>
          <%= link_to "About", pages_about_bcr_path, class: "navbar-item #{active? pages_about_bcr_path}" %>
          <%= link_to "Product", pages_about_coffee_path, class: "navbar-item #{active? pages_about_coffee_path}" %>
          <%= link_to "Bio", pages_about_us_path, class: "navbar-item #{active? pages_about_us_path}" %>
          <%= link_to "Contact", pages_contact_path, class: "navbar-item #{active? pages_contact_path}" %>
        </div>
      </div>
    </div>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BahamasCoffeeRoasters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-controller="main">
    <section class="hero is-fullheight main">
      <%= render 'layouts/navbar' %>

      <%= render 'layouts/flash' %>

      <div class="hero-body">
        <div class="container has-text-centered">
          <div class="columns">    
            <div class="column">
            </div>

            <div class="column">
              <%= yield %>
            </div>

            <div class="column">
            </div>
          </div>
        </div>
      </div>

      <%= render 'layouts/footer' %>
    </section>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for @contact, url: pages_contact_path do |f| %>
  <div class="field has-addons">
    <div class="control">
      <%= f.text_field  :first_name, required: true, class: "input", placeholder: "First name" %>
    </div>

    <div class="control">
      <%= f.text_field  :last_name, required: true, class: "input", placeholder: "Last name" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.email_field  :email, required: true, class: "input", placeholder: "Email address" %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.text_area  :message, required: true, class: "textarea", placeholder: "Message" %>
    </div>
  </div>

  <div class="field">
    <div class="control has-text-centered">
      <%= f.submit 'Send Message', class: 'button is-primary' %>
    </div>
  </div>
  <%= f.text_field :nickname, :hint => 'Leave this field blank!', hidden: true %>
<% end %>

app/views/pages/about_bcr.html.erb
<h1 class="title">
  Pages#about_bcr
</h1><br>

<h3 class="subtitle">
  app/views/pages/about_bcr.html.erb
</h3>

<figure class="image is-4by3">
  <%= image_tag("https://via.placeholder.com/128") %>
</figure><br>

<div class="content is-medium">
  <p>
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua. Ut enim ad minim veniam, quis nostrud exercitation
    ullamco laboris nisi ut aliquip ex ea commodo consequat.
  </p>
</div>

app/views/pages/about_coffee.html.erb
<h1 class="title">
  Pages#about_coffee
</h1><br>

<h3 class="subtitle">
  app/views/pages/about_coffee.html.erb
</h3>

<figure class="image is-4by3">
  <%= image_tag("https://via.placeholder.com/128") %>
</figure><br>

<div class="content is-medium">
  <p>
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua. Ut enim ad minim veniam, quis nostrud exercitation
    ullamco laboris nisi ut aliquip ex ea commodo consequat.
  </p>
</div>

app/views/pages/about_us.html.erb
<h1 class="title">
  Pages#about_us
</h1><br>

<h3 class="subtitle">
  app/views/pages/about_us.html.erb
</h3>

<figure class="image is-4by3">
  <%= image_tag("https://via.placeholder.com/128") %>
</figure><br>

<div class="content is-medium">
  <p>
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua. Ut enim ad minim veniam, quis nostrud exercitation
    ullamco laboris nisi ut aliquip ex ea commodo consequat.
  </p>
</div>

app/views/pages/contact.html.erb
<div id="contact">
  <h1 class="title">
    Pages#contact
  </h1><br>

  <h3 class="subtitle">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua.
  </h3><br>

  <%= render 'pages/form' %>
</div>

app/views/pages/landing.html.erb
<div class="hero-body">
  <div class="container has-text-centered">
    <h1 class="title">
      BAHAMAS COFFEE ROASTERS
    </h1><br>

    <h2 class="subtitle">
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna
      aliqua. Ut enim ad minim veniam, quis nostrud exercitation
      ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </h2>
  </div>
</div>